// <auto-generated />
using System;
using ClauseMatchGraphConnector.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClauseMatchGraphConnector.Migrations
{
    [DbContext(typeof(ClausematchDbContext))]
    [Migration("20250425165232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ClauseMatchGraphConnector.ClausematchApiClient.Models.LatestCategory", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "CategoryId");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "CategoryName");

                    b.Property<string>("ClausematchDocumentDocumentId")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.HasIndex("ClausematchDocumentDocumentId");

                    b.ToTable("LatestCategory");

                    b.HasAnnotation("Relational:JsonPropertyName", "latestCategories");
                });

            modelBuilder.Entity("ClauseMatchGraphConnector.Data.ClausematchDocument", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentClass")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "documentClass");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LastPublishedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "lastPublishedAt");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<string>("LatestTitle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "latestTitle");

                    b.Property<string>("LatestVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "latestVersion");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("DocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ClauseMatchGraphConnector.ClausematchApiClient.Models.LatestCategory", b =>
                {
                    b.HasOne("ClauseMatchGraphConnector.Data.ClausematchDocument", null)
                        .WithMany("LatestCategories")
                        .HasForeignKey("ClausematchDocumentDocumentId");
                });

            modelBuilder.Entity("ClauseMatchGraphConnector.Data.ClausematchDocument", b =>
                {
                    b.Navigation("LatestCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
